import Head from 'next/head';
import Image from 'next/image';
// import styles from '@/styles/Home.module.css'
import SideNavBar from '@/components/side-nav-bar';
import ProjectCard from '@/components/project-card';
import QuaterCard from '@/components/quater-card';

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Collabo About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/code-collabo-logo.png" />
      </Head>

      <div className="site-body">
        <SideNavBar />
        <main className="main-container">
          <h1>This is Code Collabo's About Page</h1>
        </main>
      </div>
    </>
  );
}
