import Head from 'next/head';
import Image from 'next/image';
// import styles from '@/styles/Home.module.css'
import SideNavBar from '@/components/side-nav-bar';
import ProjectCard from '@/components/project-card';
import QuaterCard from '@/components/quater-card';

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Collabo Intership Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/code-collabo-logo.png" />
      </Head>

      <div className="site-body">
        <SideNavBar />
        <main className="main-container">
          <div className="top-section">
            <button className="top-section-button">INTERNSHIP</button>
            <select className="top-section-select" name="year" id="year">
              <option value="2021">2021</option>
              <option value="2022">2022</option>
              <option value="2023">2023</option>
              <option value="2025">2024</option>
              <option value="2026">2025</option>
              <option value="2027">2026</option>
            </select>
          </div>

          <QuaterCard title="First Quater" />

          <QuaterCard title="Second Quater" />

          <QuaterCard title="Third Quater" />

          {/* <div className="quater-section">
            <h3 className="quater-section-title">Quater 3</h3>
            <ProjectCard title="code colabo project 1" />
            <ProjectCard title="code colabo project 2" />
            <ProjectCard title="code colabo project 3" />
            <ProjectCard title="code colabo project 4" />
          </div> */}
        </main>
      </div>
    </>
  );
}
